CLASS lcl_local_class DEFINITION CREATE PRIVATE.

  PUBLIC SECTION.
    DATA local_attribute TYPE i.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.

CLASS lcl_local_class IMPLEMENTATION.

ENDCLASS.