---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: EditorConfig

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:
  lint-editorconfig:
    runs-on: ubuntu-latest
    name: Lint for editorconfig violations
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Check for editorconfig violations
        uses: editorconfig-checker/action-editorconfig-checker@v1
