---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: EditorConfig

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  pull_request:

permissions:
  contents: read

###############
# Set the Job #
###############
jobs:
  lint-editorconfig:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Check indentation, EOL, EOF, ...
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Check for editorconfig violations
        uses: editorconfig-checker/action-editorconfig-checker@v1
