name: Check Markdown Links

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  check-links:
    name: Check links
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-pr-review
          fail_on_error: true
