name: Validate JSON data

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    # Name the Job
    name: Validate data against JSON schema

    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x (latest)
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    - name: Run validation script
      run: |
        python json-validator.py
